services:
  setup:
    extends:
      file: ./config/setup.yaml
      service: setup
    networks:
      - votcha_votcha_network
  elastic:
    extends:
      file: ./services/elastic.yaml
      service: elastic
    networks:
      - votcha_votcha_network
  kibana:
    extends:
      file: ./services/kibana.yaml
      service: kibana
    networks:
      - votcha_votcha_network
  logstash:
    extends:
      file: ./services/logstash.yaml
      service: logstash
    networks:
      - votcha_votcha_network
  filebeat:
    extends:
      file: ./services/filebeat.yaml
      service: filebeat
    networks:
      - votcha_votcha_network
volumes:
  certs:
    driver: local
  elastic_data:
    driver: local
  kibana_data:
    driver: local
  logstash_data:
    driver: local

networks:
  votcha_votcha_network:
    external: true


