services:
  app:
    build: .
    container_name: votify_meet
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/votify_meet
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${APP_PORT}:8090"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - votify_meet_network
  db:
    container_name: votify_meet_db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - votify_meet_vol:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - votify_meet_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d votify_meet" ]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  votify_meet_network:
    driver: bridge
volumes:
  votify_meet_vol: