services:
  app:
    extends:
      file: deploy/backend.yaml
      service: app
    networks:
      - votcha_votcha_network
  frontend:
    extends:
      file: deploy/frontend.yaml
      service: frontend
    networks:
      - votcha_votcha_network
    depends_on:
      grafana:
        condition: service_started
  db:
    extends:
      file: deploy/db.yaml
      service: db
    networks:
      - votcha_votcha_network
  prometheus:
    extends:
      file: monitoring/services/prometheus.yaml
      service: prometheus
    networks:
      - votcha_votcha_network
  grafana:
    extends:
      file: monitoring/services/grafana.yaml
      service: grafana
    networks:
      - votcha_votcha_network
networks:
  votcha_votcha_network:
    external: true
volumes:
  votcha_vol:
    driver: local
