input {
  tcp {
    port => 5000
  }
  beats {
    port => 5044
  }
}
filter {
  # We already have the data in json format
  # We can skip here now
  # We'll write here (GEOIP) finding location in the future
}
output {
  elasticsearch {
    index => "votify_meet-%{+YYYY.MM.dd}"
    hosts=> "${ELASTIC_HOSTS}"
    user=> "${ELASTIC_USER}"
    password=> "${ELASTIC_PASSWORD}"
    ssl_certificate_authorities => ["/usr/share/logstash/config/certs/ca/ca.crt"]
    ssl_enabled => true
  }
  stdout{
    codec => rubydebug	
  }
}
