spring.application.name=votify-meet

server.port=8090

spring.datasource.url=jdbc:postgresql://localhost:5434/votify_meet
spring.datasource.username=postgres
spring.datasource.password=enes
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.show_sql=false

# 7 days, for refresh token
jwt.refresh-token.expiration-in-seconds=604800

# You need to set this as true in production environment
app.security.cookie.secure=false

# Don't show Spring logs
spring.main.banner-mode=off

