spring.application.name=votcha

server.port=8090

spring.datasource.url=jdbc:postgresql://localhost:5434/votcha
spring.datasource.username=postgres
spring.datasource.password=enes
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.show_sql=false

# 7 days, for refresh token
jwt.refresh-token.expiration-in-seconds=604800

# You need to set this as true in production environment
app.security.cookie.secure=false

# Don't show Spring logs
spring.main.banner-mode=off

# Actuator metrics
management.endpoints.web.exposure.include=*

# throw error if the requestDtos have extra fields
spring.jackson.deserialization.fail-on-unknown-properties=true

# Remove the unnecessary logs (WARNINGS)
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
spring.jpa.open-in-view=false

# Nginx forward proxy
server.forward-headers-strategy=native

initial.admin.email=${SUPER_ADMIN_EMAIL:admin@votcha.com}
initial.admin.password=${SUPER_ADMIN_PASSWORD:superadmin}