apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: votcha-dev
spec:
  type: ClusterIP
  selector:
    app: votcha
    component: frontend
    tier: ui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80