apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: votcha-dev
spec:
  type: ClusterIP
  selector:
    app: votcha
    component: logging
    tier: elk
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
