services:
  postgres:
    image: postgres
    env:
      POSTGRES_DB: votify_meet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: enes
    ports:
      - 5434:5432 # Uygulaman 5434 beklediği için GitHub'da da bu portu açıyoruz
    options: >-
      --health-cmd pg_isready
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5
